# .pages.yml
# Финальная конфигурация для Pages CMS

# 1. Секция MEDIA
# Определяет, где хранятся и куда загружаются изображения
media:
  - name: "images"
    label: "Изображения"
    input: "images"          # Папка в репозитории
    output: "/images"        # Путь, который будет вставляться в контент
    extensions: ["jpg", "png", "svg", "webp"] # Разрешенные типы

# 2. Секция CONTENT
# Определяет редактируемые файлы с данными
content:
  # --- ФАЙЛ 1: Главная (Видение лидера) ---
  - name: "index"
    label: "Главная (Видение лидера)"
    type: "file"                  
    path: "_data/index.json"      
    format: "json"                
    fields:                       
      - { name: "title", label: "Заголовок (SEO)", type: "string" } 
      - name: "hero"
        label: "Главный блок (Hero)"
        type: "object"            
        fields:
          - { name: "image", label: "Изображение (куб)", type: "image" } 
          - { name: "alt", label: "Alt текст", type: "string" }
          - { name: "h1", label: "Заголовок H1", type: "string" }
          - { name: "lead", label: "Подзаголовок", type: "text" }
      - name: "content_body"
        label: "Основной контент (Манифест)"
        type: "rich-text"         
      - name: "regulation_body"
        label: "Секция 'Регуляция'"
        type: "rich-text"

  # --- ФАЙЛ 2: Холистический подход ---
  - name: "holistic"
    label: "Холистический подход"
    type: "file"
    path: "_data/holistic.json"
    format: "json"
    fields:
      - { name: "title", label: "Заголовок (SEO)", type: "string" }
      - name: "hero_image"
        label: "Верхнее изображение"
        type: "object"
        fields:
          - { name: "src", label: "Изображение", type: "image" }
          - { name: "alt", label: "Alt текст", type: "string" }
      - name: "author"
        label: "Карточка автора"
        type: "object"
        fields:
          - { name: "name", label: "Имя автора", type: "string" }
          - { name: "role", label: "Должность/Роль", type: "string" }
          - { name: "photo_src", label: "Фото автора", type: "image" }
          - { name: "photo_alt", label: "Alt текст фото", type: "string" }
      # --- ВАЖНЫЕ ИСПРАВЛЕНИЯ (см. ниже) ---
      - name: "intro"
        label: "Введение (правая колонка)"
        type: "object"
        fields:
          - { name: "h1", label: "Заголовок H1", type: "string" }
          - { name: "lead", label: "Подзаголовок", type: "text" }
          - { name: "h2", label: "Заголовок H2", type: "string" }
          - { name: "intro_text", label: "Текст введения", type: "text" }
      # ---
      - name: "content_body"
        label: "Основной контент (статья)"
        type: "rich-text"
        description: "Весь текст, начиная с 'Основных принципов'"

  # --- ФАЙЛ 3: Апитерапия ---
  - name: "apitherapy"
    label: "Апитерапия"
    type: "file"
    path: "_data/apitherapy.json"
    format: "json"
    fields:
      - { name: "title", label: "Заголовок (SEO)", type: "string" }
      - name: "hero"
        label: "Шапка страницы"
        type: "object"
        fields:
          - { name: "image", label: "Изображение (шапка)", type: "image" }
          - { name: "alt", label: "Alt текст", type: "string" }
          - { name: "h1", label: "Заголовок H1", type: "string" }
          - { name: "lead", label: "Подзаголовок", type: "text" }
      - name: "intro"
        label: "Вводный блок"
        type: "object"
        fields:
          - name: "photo"
            label: "Фото"
            type: "object"
            fields:
              - { name: "src", label: "Изображение", type: "image" }
              - { name: "alt", label: "Alt текст", type: "string" }
          - { name: "text", label: "Текст введения", type: "rich-text" }
      - name: "conditions_body"
        label: "Секция 'Перечень сфер'"
        type: "rich-text"
      - name: "how_it_works_body"
        label: "Секция 'Как это работает'"
        type: "rich-text"
      - name: "gallery"
        label: "Галерея"
        type: "object" # Меняем на type: object
        list: # Используем ключевое слово list как объект для настроек
          collapsible:
            # summary — это задокументированный способ задания заголовка для элементов-объектов
            summary: "🖼️ {fields.caption} ({fields.image_src})"
        fields: # Поля для каждого элемента списка
          - { name: "image_src", label: "Изображение", type: "image" }
          - { name: "alt", label: "Alt текст", type: "string" }
          - { name: "caption", label: "Подпись", type: "string" }
      - name: "notes_body"
        label: "Секция 'Важно (безопасность)'"
        type: "rich-text"